
<div class="row">
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('instagram', array('action' => 'index')));
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <div class="form-group col-lg-6">
        <?php
        echo $this->formtext($form->get('longtitude'));
        echo "<span style='color:red'>" . $this->formElementErrors($form->get('longtitude')) . "</span>";
        ?>
    </div>
    <div class="form-group col-lg-6">
        <?php
        echo $this->formtext($form->get('latitude'));
        echo "<span style='color:red'>" . $this->formElementErrors($form->get('latitude')) . "</span>";
        ?>
    </div>
    <div class="form-group col-lg-6">
        <?php
        echo $this->formtext($form->get('distance'));
        echo "<span style='color:red'>" . $this->formElementErrors($form->get('distance')) . "</span>";
        ?>
    </div>
    <div class="col-lg-12">
        <button type="submit" class="btn btn-success">Save</button>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div> 
<br>
<table id="example" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>No.</th>
            <th>Name</th>
            <th>Create time</th>
            <th>Likes</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
            <th>No.</th>
            <th>Name</th>
            <th>Create time</th>
            <th>Likes</th>
        </tr>
    </tfoot>
    <tbody>
        <?php
        $i = 1;
        if (isset($result)) {
            // print_r($result);exit;
            $location="";
            foreach ($result->data as $rs):
                ?>
                <tr>
                    <td><?php echo $i; ?></td>
                    <td><?php echo $rs->user->full_name; ?></td>
                    <td><?php echo date("d-m-Y", $rs->created_time); ?></td>
                    <td><?php echo $rs->likes->count; ?></td>
                </tr>
                <?php
                $images[$i] = $rs->images->standard_resolution;
                if($i==1){
                    $firstLocation =$rs->location->latitude.",".$rs->location->longitude;
                }
                if($i==count($result->data)){
                $location .= "["."'".$rs->user->username."'".",".$rs->location->latitude.",".$rs->location->longitude."]";
                }else{
                 $location .= "["."'".$rs->user->username."'".",".$rs->location->latitude.",".$rs->location->longitude."],";
                }
                $i++;
            endforeach;
            ?>
        </tbody>
    </table>
    <br>
    <div class="row">
        <div id="slider-carouselMain" class="carousel slide" data-ride="carousel">

            <div class="carousel-inner" id='swiper-container-Main'>
                <?php
                $i = 0;
                foreach ($images as $im):
                    //   print_r($im->url);
                    $i++;
                    ?>
                    <div class="item <?php
                    if ($i == 1) {
                        echo 'active';
                    }
                    ?> no-padding">
                        <div class="col-sm-12">
                            <img src="<?php echo $im->url ?>" class="girl img-responsive img-slide" alt="" />
                          </div>
                    </div>
                <?php endforeach; ?>
            </div>

            <ol class="carousel-indicators">
                <?php for ($i = 0; $i < count($images); $i++) { ?>
                    <li data-slide-to="0" data-target="#slider-carouselMain" class=""></li>
                <?php } ?>
            </ol>
            <a id="mainSlidePrev" class="left carousel-control btn-slide" href="#slider-carouselMain" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>

            <a id="mainSlidePNext" class="right carousel-control btn-slide" href="#slider-carouselMain" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
    <br>
    <div class="row">
        <style>
            #map-canvas {
                width: 1000px;
                height: 400px;
            }
        </style>
        <script src="https://maps.googleapis.com/maps/api/js"></script>
        <?php echo "<script>".
            "var markers=[".
               $location.
            "];
        </script>"?>
        <script>
            function initialize() {
                var mapCanvas = document.getElementById('map-canvas');
                var mapOptions = {
                    center: new google.maps.LatLng(<?php echo $firstLocation; ?>),
                    zoom: 10,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                }
                map = new google.maps.Map(mapCanvas, mapOptions);
                
            var infowindow = new google.maps.InfoWindow(), marker, i;
            for (i = 0; i < markers.length; i++) {
                marker = new google.maps.Marker({
                    position: new google.maps.LatLng(markers[i][1], markers[i][2]),
                    map: map
                });
                google.maps.event.addListener(marker, 'click', (function (marker, i) {
                    return function () {
                        infowindow.setContent(markers[i][0]);
                        infowindow.open(map, marker);
                    }
                })(marker, i));
            }
            }
            //

            //
            google.maps.event.addDomListener(window, 'load', initialize);
            //for draw marker
            
            //
        </script>


        <div id="map-canvas"></div>
    </div>
<?php }
?>
