   
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url('user', array('action' => 'login.phtml')));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    ?>
                    <fieldset>
                        <div class="form-group">
                            <?php
                            echo $this->formtext($form->get('username'));
                            echo "<span style='color:red'>" . $this->formElementErrors($form->get('username')) . "</span>";
                            ?>
                        </div>
                        <div class="form-group">
                            <?php
                            echo $this->formPassword($form->get('password'));
                            echo "<span style='color:red'>" . $this->formElementErrors($form->get('password')) . "</span>";
                            ?>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input name="remember" type="checkbox" value="Remember Me">Remember Me
                            </label>
                        </div>
                         <?php if(isset($err)) echo "<div class='form-group'><span style='color:red'>".$err."</span></div>";?>

                        <!-- Change this to a button or input when using this as a form -->
                        <?php echo $this->formsubmit($form->get('Login')); ?>
                    </fieldset>
                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- jQuery -->
<script src="../bower_components/jquery/dist/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="../bower_components/metisMenu/dist/metisMenu.min.js"></script>

<!-- Custom Theme JavaScript -->
<script src="../dist/js/sb-admin-2.js"></script>

